// This file is auto-generated by entanglement.javascript_schema. DO NOT EDIT.

function register_schema(registry) {
  registry._schemaItem("SyncOwner", ["_sync_owner"], ["_sync_owner"]);
  registry._schemaItem(
    "ProvidedDependency",
    ["injector_id", "key"],
    ["key", "injector_id", "provider_id", "_sync_owner"],
  );
  registry._schemaItem(
    "ProviderInfo",
    ["id"],
    ["id", "state", "value_repr", "value_injector_id", "_sync_owner"],
  );
  registry._schemaItem(
    "StaticDependency",
    ["provider_id", "key"],
    ["provider_id", "key", "provided_by", "_sync_owner"],
  );
  registry._schemaItem(
    "InjectorInfo",
    ["id"],
    ["id", "parent_id", "description", "_sync_owner"],
  );
  registry._schemaItem(
    "TaskInfo",
    ["instance_injector_id", "stamp"],
    [
      "instance_injector_id",
      "stamp",
      "description",
      "running",
      "should_run",
      "last_run",
      "last_failure",
      "_sync_owner",
    ],
  );
  registry._schemaItem(
    "FailedInstantiation",
    ["injector_id", "key"],
    ["injector_id", "key", "exception", "dependency", "_sync_owner"],
  );
  registry._schemaItem(
    "WhsEntangledNetwork",
    ["name"],
    ["name", "network", "injector_id", "_sync_owner"],
  );
}
export default register_schema;
